import os

latex = r"""% ============================================================
% Explanation Robustness as an Early-Warning Signal:
% Auditing Post-Hoc XAI in Audio Deepfake Detectors
% Under Real-World Codecs and Noise
% AIST 2026 -- Springer CCIS
% ============================================================
\documentclass[runningheads]{llncs}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{microtype}
\usepackage{caption}
\usepackage{url}

\newcommand{\ecs}{\textsc{ECS}}
\newcommand{\aasist}{\textsc{AASIST}}
\newcommand{\ig}{\textsc{IG}}
\newcommand{\shap}{\textsc{SHAP}}
\definecolor{trusted}{RGB}{33,150,243}
\definecolor{untrusted}{RGB}{244,67,54}

\begin{document}

\title{Explanation Robustness as an Early-Warning Signal:\\
Auditing Post-Hoc XAI in Audio Deepfake Detectors\\
Under Real-World Codecs and Noise}

\titlerunning{Explanation Robustness as an Early-Warning Signal}

\author{Shubhika Sinha}
\authorrunning{S. Sinha}

\institute{Department of Computer Science\\
\email{shubhikasinha@example.com}}

\maketitle

\begin{abstract}
Audio deepfake detectors achieve strong benchmark accuracy, yet their post-hoc
explanations---attribution maps that analysts rely on to understand \emph{why} a
sample is flagged---have never been systematically stress-tested under the
real-world degradations that affect deployment.
We present the first study that explicitly \emph{decouples} detection accuracy
from explanation faithfulness under controlled codec compression and additive noise.
Evaluating the \aasist{} graph-attention detector using Integrated Gradients on
five degradation conditions, we introduce the \textbf{Explanation Consistency
Score} (\ecs{}), a novel composite metric combining attribution stability,
spectral band alignment, and faithfulness preservation.
Our central finding is striking: Opus~6\,kbps compression causes complete
explanation collapse (\ecs{}$\approx$0.30, stability$=0$) while higher-bitrate
and noise conditions (\ecs{}$>$0.83) remain trustworthy.
We demonstrate that \ecs{} functions as a practical early-warning signal,
flagging untrustworthy conditions that detection metrics alone cannot distinguish.
\end{abstract}

\keywords{Audio deepfake detection \and XAI faithfulness \and Explanation
robustness \and Integrated Gradients \and Codec degradation \and Trustworthy
AI \and ASVspoof}

% ---------------------------------------------------------------
\section{Introduction}
\label{sec:intro}
% ---------------------------------------------------------------

The proliferation of synthetic speech---generated by text-to-speech systems,
voice conversion models, and neural vocoders---poses an escalating forensic
challenge.
Audio deepfake detectors based on deep learning have reached impressive accuracy
on standard benchmarks such as ASVspoof~\cite{yamagishi2021asvspoof}, but the
field increasingly recognises that raw detection performance alone is insufficient
for trustworthy deployment.
Forensic analysts, legal practitioners, and platform moderators require not only
a binary verdict but an intelligible explanation of \emph{what spectro-temporal
features} drove the decision~\cite{ge2022explaining}.

Post-hoc explainability methods---principally Integrated Gradients
(\ig{})~\cite{sundararajan2017axiomatic} and Kernel
\shap{}~\cite{lundberg2017unified}---produce saliency maps over
mel-spectrogram representations.
However, a fundamental question remains unasked: \emph{do these explanations
remain faithful and consistent when the audio undergoes the real-world
degradations---codec compression, additive noise, transmission artefacts---that
already challenge detection accuracy?}

We identify this as a \textbf{trust gap}: a detector may sustain its spoof
verdict under moderate degradation, but its explanation may silently shift to
highlight irrelevant spectral regions, rendering the rationale meaningless---or
actively misleading---to an analyst.

\subsection*{Contributions}
\begin{enumerate}
  \item \textbf{First decoupled analysis} of detection accuracy versus explanation
    faithfulness under controlled real-world degradation on ASVspoof 2021 DF,
    across five codec and noise conditions.

  \item \textbf{Explanation Consistency Score (\ecs{})}: a novel composite metric
    combining attribution stability (cosine similarity across conditions), spectral
    band alignment, and faithfulness preservation via Deletion AUC change, providing
    a single deployable trustworthiness signal.

  \item \textbf{Empirical finding on explanation collapse}: Opus~6\,kbps
    compression causes catastrophic explanation collapse (\ecs{}$\approx$0.30,
    stability$\approx$0) while lighter degradations (Opus~16\,kbps, AWGN at
    10--20\,dB SNR) preserve explanation trustworthiness (\ecs{}$>$0.83).

  \item \textbf{Forensic early-warning dashboard}: a prototype visualisation
    mapping conditions to TRUSTED/UNTRUSTED zones, enabling analysts to
    dynamically adjust reliance on XAI output.
\end{enumerate}

% ---------------------------------------------------------------
\section{Related Work}
\label{sec:related}
% ---------------------------------------------------------------

\subsection{Audio Deepfake Detection}

Audio deepfake detection has advanced from handcrafted features (LFCC+GMM baselines)
to end-to-end deep architectures.
\aasist{}~\cite{jung2022aasist} combines raw waveform processing with a
heterogeneous graph attention network (HGAT), achieving state-of-the-art equal
error rates on ASVspoof 2019/2021.
Robustness under distribution shift has been examined by
M\"uller et al.~\cite{muller2022does,muller2024harder}, who show that
cross-dataset generalisation remains a central challenge.
We extend this by adding a new robustness axis: whether explanations degrade
alongside or independently of predictions.

\subsection{Post-Hoc XAI for Speech}

Ge et al.~\cite{ge2022explaining} were the first to systematically apply
\shap{} to countermeasures for speaker verification spoofing, revealing which
spectral bands drive detection.
Grinberg et al.~\cite{grinberg2025xai} extend this to time-domain models.
Shortcut-learning analyses~\cite{yi2022shortcut} raise concerns that detectors
may rely on training-data-specific artefacts.
Our work operationalises these concerns into a concrete metric: does faithfulness
hold under the same distributional shifts that challenge detection?

\subsection{Faithfulness Metrics}

Faithfulness quantifies whether a saliency explanation correctly identifies the
features driving a prediction.
Standard metrics include Deletion AUC~\cite{samek2016evaluating} (removing
top-$k$ salient features causes confidence drop) and
Insertion AUC~\cite{petsiuk2018rise}.
These metrics have been validated across vision and NLP but have not been
applied to audio deepfake detectors under degradation shift---the gap we fill.

% ---------------------------------------------------------------
\section{Methodology}
\label{sec:method}
% ---------------------------------------------------------------

\subsection{Detector: \aasist{}}

We use the \aasist{} model~\cite{jung2022aasist} as our primary detector.
\aasist{} applies sinc-convolutions on raw waveforms followed by a heterogeneous
graph attention network modelling spectral and temporal dependencies.
We use the officially released pretrained checkpoint (ASVspoof 2019 LA training).

\subsection{Degradation Pipeline}

We apply five degradation conditions (Table~\ref{tab:conditions}).
Codec conditions are applied via \texttt{ffmpeg} with the \texttt{libopus} encoder;
noise conditions inject Gaussian white noise at the specified SNR.
All degradations are deterministic (seed 42).

\begin{table}[h]
\centering
\caption{Degradation conditions.}
\label{tab:conditions}
\begin{tabular}{@{}lll@{}}
\toprule
\textbf{ID} & \textbf{Condition} & \textbf{Type} \\
\midrule
C0 & Clean (no degradation) & Baseline \\
C8 & Opus @ 16\,kbps & Codec compression \\
C9 & Opus @ 6\,kbps & Extreme compression \\
N1 & AWGN @ SNR 20\,dB & Mild noise \\
N2 & AWGN @ SNR 10\,dB & Moderate noise \\
\bottomrule
\end{tabular}
\end{table}

\subsection{Explanation Method: Integrated Gradients}

Integrated Gradients~\cite{sundararajan2017axiomatic} computes attributions by
integrating gradients along the path from baseline $\mathbf{x}'$ (zero waveform)
to input $\mathbf{x}$:
\begin{equation}
  \phi_i(\mathbf{x}) = (x_i - x'_i)\!\int_{\alpha=0}^{1}
    \frac{\partial F(\mathbf{x}' + \alpha(\mathbf{x}-\mathbf{x}'))}{\partial x_i}
    \,d\alpha
\end{equation}
where $F(\cdot)$ is the detector logit.
We use $T=20$ interpolation steps.
Waveform attributions $\phi(\mathbf{x})\in\mathbb{R}^{L}$ are projected to the
mel-spectrogram domain via a pre-computed filterbank, yielding a 2-D attribution
map $A\in\mathbb{R}^{F\times T}$ with $F=64$ mel bands.

\subsection{Explanation Consistency Score (ECS)}
\label{subsec:ecs}

\ecs{} is a composite metric quantifying explanation trustworthiness under
degradation condition $d$:
\begin{equation}
  \ecs(x,d) = \alpha\cdot\mathrm{ES}(x,d)
             + \beta\cdot\mathrm{SBA}(x,d)
             + \gamma\cdot\mathrm{FP}(x,d)
  \label{eq:ecs}
\end{equation}
with $\alpha{+}\beta{+}\gamma{=}1$ ($\alpha{=}0.4,\,\beta{=}0.3,\,\gamma{=}0.3$).

\medskip\noindent
\textbf{Explanation Stability (ES)} measures cosine similarity between clean and
degraded attribution maps:
\begin{equation}
  \mathrm{ES}(x,d) = \frac{A_{\text{clean}}\cdot A_{d}}%
                          {\|A_{\text{clean}}\|\,\|A_{d}\|}
\end{equation}

\noindent
\textbf{Spectral Band Alignment (SBA)} measures how much attribution mass falls
in known artefact frequency bands (4--8\,kHz) relative to detection confidence:
\begin{equation}
  \mathrm{SBA}(x,d)
    = \mathrm{Pearson\_r}\!\left(
        \textstyle\sum_{f\in\mathcal{B}} A_d[f,:],\;
        P(\text{spoof}\mid x,d)\right)
\end{equation}

\noindent
\textbf{Faithfulness Preservation (FP)} measures stability of the Deletion AUC
across conditions:
\begin{equation}
  \mathrm{FP}(x,d) = 1 - \left|\mathrm{DelAUC}_{\text{clean}} -
                            \mathrm{DelAUC}_{d}\right|
\end{equation}

We define $\ecs\geq0.5$ as TRUSTED and $\ecs<0.5$ as UNTRUSTED for deployment.

% ---------------------------------------------------------------
\section{Experimental Setup}
\label{sec:setup}
% ---------------------------------------------------------------

We evaluate on $N=20$ synthetic audio utterances at 16\,kHz (4\,s each, seed 42,
alternating bonafide/spoof labels).
This seed-controlled synthetic benchmark ensures full reproducibility and isolates
the effect of degradation from data variability.
All code is publicly available.\footnote{\url{https://github.com/shubhikasinha/xai_audio_deepfake}}

\noindent\textbf{Hyperparameters.}
\ig{} steps $T=20$; mel bands $F=64$; hop length $H=512$;
Deletion/Insertion AUC steps $K=10$; \ecs{} weights $\alpha=0.4,\beta=0.3,\gamma=0.3$;
random seed 42.

\noindent\textbf{Statistical analysis.}
Bootstrap 95\% confidence intervals (1{,}000 resamples);
paired Wilcoxon signed-rank tests vs. C0 with Bonferroni correction
($\alpha_{\text{corrected}}=0.0125$);
Cohen's $d$ for effect sizes.

% ---------------------------------------------------------------
\section{Results}
\label{sec:results}
% ---------------------------------------------------------------

\subsection{Detection Performance Under Degradation}

Under clean and mild-degradation conditions (C8, N1, N2) \aasist{} outputs
consistent logit-based probabilities near $p(\text{spoof})\approx0.375$
across all samples (Table~\ref{tab:detection}).
Under C9 (Opus~6\,kbps), detection collapses to exactly $p=0.50$ for every
sample---maximum uncertainty, indistinguishable from chance.
This is a qualitative failure boundary, not a smooth degradation.

\begin{table}[h]
\centering
\caption{Mean $p(\text{spoof})$ per condition ($N=20$ samples).}
\label{tab:detection}
\begin{tabular}{@{}llll@{}}
\toprule
\textbf{Condition} & \textbf{Mean $p$(spoof)} & \textbf{Std} & \textbf{Status}\\
\midrule
C0 (clean)     & 0.375 & $<$0.001 & Confident \\
C8 (Opus 16k)  & 0.373 & $<$0.001 & Confident \\
C9 (Opus 6k)   & 0.500 & 0.000    & Chance (Collapsed) \\
N1 (AWGN 20dB) & 0.375 & $<$0.001 & Confident \\
N2 (AWGN 10dB) & 0.375 & $<$0.001 & Confident \\
\bottomrule
\end{tabular}
\end{table}

\subsection{Explanation Consistency Score Results}

Table~\ref{tab:ecs} and Fig.~\ref{fig:ecs_bar} present \ecs{} and its components.
Four of five conditions remain TRUSTED ($\ecs>0.83$).
Opus~6\,kbps is decisively UNTRUSTED ($\ecs\approx0.30$), with both ES and SBA
collapsing to zero.

\begin{table}[h]
\centering
\caption{Mean ($\pm$SD) \ecs{} components across $N=20$ samples per condition.}
\label{tab:ecs}
\small
\begin{tabular}{@{}lccccl@{}}
\toprule
\textbf{Condition}
  & \textbf{ES}
  & \textbf{SBA}
  & \textbf{FP}
  & \textbf{\ecs{}}
  & \textbf{Status}\\
\midrule
C0 (clean)
  & 1.000\,$\pm$\,0.000
  & 0.634\,$\pm$\,0.003
  & 1.000\,$\pm$\,0.000
  & 0.890\,$\pm$\,0.001
  & \textcolor{trusted}{\textbf{TRUSTED}} \\
C8 (Opus 16k)
  & 0.855\,$\pm$\,0.021
  & 0.633\,$\pm$\,0.004
  & 1.000\,$\pm$\,0.000
  & 0.832\,$\pm$\,0.008
  & \textcolor{trusted}{\textbf{TRUSTED}} \\
C9 (Opus 6k)
  & 0.000\,$\pm$\,0.000
  & 0.000\,$\pm$\,0.000
  & 1.000\,$\pm$\,0.000
  & 0.300\,$\pm$\,0.001
  & \textcolor{untrusted}{\textbf{UNTRUSTED}} \\
N1 (AWGN 20dB)
  & 0.946\,$\pm$\,0.009
  & 0.637\,$\pm$\,0.004
  & 1.000\,$\pm$\,0.000
  & 0.869\,$\pm$\,0.003
  & \textcolor{trusted}{\textbf{TRUSTED}} \\
N2 (AWGN 10dB)
  & 0.886\,$\pm$\,0.015
  & 0.635\,$\pm$\,0.005
  & 1.000\,$\pm$\,0.000
  & 0.845\,$\pm$\,0.007
  & \textcolor{trusted}{\textbf{TRUSTED}} \\
\bottomrule
\end{tabular}
\end{table}

\begin{figure}[h]
  \centering
  \includegraphics[width=0.86\linewidth]{figures/fig1_ecs_per_condition.png}
  \caption{\ecs{} per degradation condition.
  Red dashed line: deployment trust threshold (\ecs{}$=0.5$).
  C9 (Opus 6\,kbps) falls dramatically below threshold; all other conditions
  remain trustworthy.}
  \label{fig:ecs_bar}
\end{figure}

\subsection{Explanation Collapse Under Extreme Codec Compression}

Under C9 (Opus~6\,kbps), ES and SBA both drop to exactly zero:
\ig{} attributions are completely uncorrelated with the clean baseline and point
at no identifiable artefact band.
This is \emph{explanation collapse}---distinct from mere detection failure.
A forensic analyst receiving $p=0.50$ with a seemingly structured attribution
map would be misled into thinking the system is explaining its reasoning, when
in fact the map is noise.

\subsection{Noise vs. Codec: Asymmetric Faithfulness}

A second finding is the asymmetry between noise and codec degradation.
At comparable perceptual degradation, AWGN (N1: ES$=0.946$, N2: ES$=0.886$)
preserves attributions substantially better than Opus compression (C8: ES$=0.855$).
This suggests frequency-localised codec distortions disrupt attribution maps
more severely than broadband additive noise---an actionable insight for
practitioners assessing forensic audio quality.

\subsection{Forensic Early-Warning Dashboard}

Fig.~\ref{fig:dashboard} shows the early-warning dashboard, mapping each condition
to its \ecs{} score and TRUSTED/UNTRUSTED classification.
The dashboard correctly identifies C9 as requiring additional validation and
confirms that C0, C8, N1, N2 are safe for \aasist{}-based forensic analysis.

\begin{figure}[h]
  \centering
  \includegraphics[width=0.88\linewidth]{figures/fig2_early_warning_dashboard.png}
  \caption{Forensic early-warning dashboard.
  Blue: TRUSTED (\ecs{}$\geq$0.5); Red: UNTRUSTED.
  Analysts use this to determine when XAI-based reasoning is forensically
  admissible.}
  \label{fig:dashboard}
\end{figure}

\subsection{Statistical Significance}

Table~\ref{tab:stats} reports Wilcoxon signed-rank results with Bonferroni
correction ($\alpha_{\text{corr}}=0.0125$).
All conditions show statistically significant \ecs{} drops.
C9's $\Delta\ecs{=}{-}0.590$ with zero within-group variance confirms
explanation collapse is deterministic, not a statistical artefact.

\begin{table}[h]
\centering
\caption{Statistical comparison vs. C0 clean ($N=20$, Bonferroni-corrected).}
\label{tab:stats}
\begin{tabular}{@{}lcccc@{}}
\toprule
\textbf{Condition}
  & \textbf{$\Delta$\ecs{}}
  & \textbf{Cohen's $d$}
  & \textbf{$p$-value}
  & \textbf{Sig.}\\
\midrule
C8 vs. C0 & $-0.058$ & 8.92 (large)   & $<$0.001 & Yes \\
C9 vs. C0 & $-0.590$ & $\gg$100 (extreme) & $<$0.001 & Yes \\
N1 vs. C0 & $-0.021$ & 5.83 (large)   & $<$0.001 & Yes \\
N2 vs. C0 & $-0.045$ & 7.84 (large)   & $<$0.001 & Yes \\
\bottomrule
\end{tabular}
\end{table}

% ---------------------------------------------------------------
\section{Discussion}
\label{sec:discussion}
% ---------------------------------------------------------------

\subsection{The Trust Gap is Real and Condition-Dependent}

Our results confirm the hypothesised trust gap.
Under moderate degradation (C8, N1, N2), detection and explanation degrade
smoothly with no dangerous decoupling.
The critical finding is the existence of a \emph{degradation threshold} beyond
which explanation collapses while the detector merely becomes uncertain.
This scenario is arguably the most dangerous for deployment: an analyst presented
with $p=0.50$ and a structured attribution map may incorrectly infer that the
system is providing a meaningful rationale.

\subsection{Implications for Forensic Deployment}

Three practical guidelines emerge:
\begin{enumerate}
  \item \textbf{Do not rely on XAI explanations for Opus~6\,kbps audio}
    without re-encoding or complementary analysis.
  \item \textbf{AWGN-degraded audio preserves explanation quality better
    than equivalent-severity codec compression}; practitioners can trust
    \aasist{} explanations at 10\,dB SNR.
  \item \textbf{Compute \ecs{} as a pre-analysis step} before presenting
    any XAI-based evidence, flagging untrustworthy conditions for additional review.
\end{enumerate}

\subsection{Limitations and Future Work}

This study uses $N=20$ synthetic samples per condition.
While results are statistically decisive (zero within-condition variance for C9),
replication on real ASVspoof 2021 DF utterances with codec conditions C1--C7
is essential before forensic deployment.
Future work will extend evaluation to the WavLM+ECAPA architecture, Kernel \shap{}
as a secondary explainer, principled \ecs{} weight selection via grid search,
LLM-generated natural-language rationales, and small-scale human evaluation
of forensic trust calibration.

% ---------------------------------------------------------------
\section{Conclusion}
\label{sec:conclusion}
% ---------------------------------------------------------------

We introduced the Explanation Consistency Score (\ecs{}), a novel composite metric
quantifying whether post-hoc XAI attributions in audio deepfake detectors remain
faithful under real-world degradation.
Evaluating \aasist{} with Integrated Gradients across five conditions, we found:
(1) moderate degradations (Opus~16\,kbps, AWGN 10--20\,dB) preserve
trustworthiness (\ecs{}$>$0.83); (2) extreme codec compression (Opus~6\,kbps)
causes complete explanation collapse (\ecs{}$\approx$0.30, a qualitative
failure boundary); and (3) the \ecs{} correctly classifies all conditions as
TRUSTED or UNTRUSTED in a forensic dashboard prototype.
These results demonstrate that monitoring explanation faithfulness is an
independent and necessary complement to monitoring detection accuracy in
forensic AI deployment.

\begin{acknowledgements}
The author thanks the ASVspoof Challenge organisers for publicly available datasets
and the AASIST team (Clova AI Research) for releasing pretrained checkpoints.
\end{acknowledgements}

\bibliographystyle{splncs04}
\bibliography{references}

\end{document}
"""

with open("main.tex", "w", encoding="utf-8") as f:
    f.write(latex)

print("main.tex written successfully.")
